### ISSUE TITLE
Tasks Autosave

### ISSUE THREAD

**Issue by lululeon** [lululeon/vuedo#37]
Add auto-save feature that saves edits to Indexed DB in the background (via service workers and appropriate Indexed DB API - need to research).

## Task breakdown
- [x] update build to incl service workers
- [x] impl basic connection to indexdb (create tasks db on activate)
- [x] map vuex to indexdb entries (tasks only at this point)
- [x] on import: populate db (batch insert)
- [x] on update: replace db obj
- [x] on start: look in db first

## Acceptance criteria
- ~[ ] Auto-saves **tasks** every x minutes~
- [x] On close and reopen app, App reloads from Indexed DB, else displays current message to create new tasks.

**Comment by lululeon** [comment]
AHA moment: Will only need service workers for background tasks, so although this is stubbed out will not flesh out on this ticket at this time. Will use vuex-persist for basic persistence for now to complete autosave behavior. Analytics and task list mgt tickets in future will use service workers.

**Comment by lululeon** [comment]
Closed via 238cf62
